#!/usr/bin/env bash
# Reproduces the WordPress demo from scratch: downloads WP core + the SQLite
# Database Integration plugin (no MySQL needed), configures wp-config.php,
# runs the installer, and activates the srm-demo theme.
#
# Only wp-content/themes/srm-demo/ is source-controlled — everything else
# here is regenerated by this script (see ../.gitignore).
set -euo pipefail

cd "$(dirname "$0")"
DEMO_DIR="$(pwd)"

command -v php >/dev/null || { echo "PHP not found. Install with: brew install php"; exit 1; }
command -v wp >/dev/null || { echo "WP-CLI not found. Install with: brew install wp-cli"; exit 1; }

WP="php -d memory_limit=512M $(command -v wp)"

if [ ! -f "$DEMO_DIR/wp-load.php" ]; then
    echo "==> Downloading WordPress core"
    $WP core download --path="$DEMO_DIR" --locale=fr_FR
fi

if [ ! -d "$DEMO_DIR/wp-content/plugins/sqlite-database-integration" ]; then
    echo "==> Downloading SQLite Database Integration plugin"
    curl -sL -o /tmp/sqlite-plugin.zip \
        "https://downloads.wordpress.org/plugin/sqlite-database-integration.latest-stable.zip"
    unzip -q /tmp/sqlite-plugin.zip -d "$DEMO_DIR/wp-content/plugins/"
    rm /tmp/sqlite-plugin.zip
fi

cp "$DEMO_DIR/wp-content/plugins/sqlite-database-integration/db.copy" "$DEMO_DIR/wp-content/db.php"

if [ ! -f "$DEMO_DIR/wp-config.php" ]; then
    echo "==> Generating wp-config.php (DB creds are dummy values — unused by the SQLite drop-in)"
    $WP config create --path="$DEMO_DIR" --skip-check \
        --dbname=srm_demo --dbuser=srm_demo --dbpass=srm_demo --dbhost=localhost
fi

if ! $WP core is-installed --path="$DEMO_DIR" 2>/dev/null; then
    echo "==> Running the WordPress installer"
    $WP core install --path="$DEMO_DIR" \
        --url="http://localhost:8081" \
        --title="SRM-SM (Démo WordPress)" \
        --admin_user=admin \
        --admin_password=srm-demo-2026 \
        --admin_email=demo@srm-sm.local \
        --skip-email
    $WP plugin activate sqlite-database-integration --path="$DEMO_DIR"
    $WP option update permalink_structure '/%postname%/' --path="$DEMO_DIR"
fi

$WP theme activate srm-demo --path="$DEMO_DIR"

echo "==> Done. Start the site with:"
echo "    php -S localhost:8081 -t $DEMO_DIR"
echo "    (admin: http://localhost:8081/wp-admin — admin / srm-demo-2026)"
